### ISSUE TITLE
Using "filter" flag seems to include filtered files

### ISSUE THREAD

**Issue by GavinRay97** [Felerius/cpp-amalgamate#3]
Hiya, thanks for such a useful tool!

I have a directory which contains third-party code at "./utils/libraries"
There is a primary `includes.h` file which contains:

```cpp
#include "utils/libraries/imgui/imgui.h"
#include "utils/libraries/FOOBAR"
// etc
```

When I run the following:
```sh
# Pipe every .cpp file not in "./utils/libraries" into "cpp-amalgamate"
$ find . -path ./utils/libraries -prune -o -name "*.cpp" -type f -print | \
  xargs cpp-amalgamate -v --filter "utils/libraries/**" -o hunt_amalgamated.cpp -d "./"
```

I get:
```
[INFO ] Writing to "hunt_amalgamated.cpp"
[INFO ] Processing source file "entity.cpp"
[INFO ] Processing "entity.cpp"
[INFO ] Processing "includes.h"
[INFO ] Processing "imgui.h"
[INFO ] Processing <OTHER THIRD-PARTY LIBRARIES>
```

And the source in `utils/libraries` is inlined into the amalgam.

Do you know what I am doing wrong?
Thank you!

**Comment by Felerius** [comment]
Hi,

the filters are applied to the absolute path of the include not the relative one specified in the `#include "..."`, so it should probably work if you change it to `--filter "**/utils/libraries/**`.

I'm not super happy with how it works right now, a filter like yours should just work. When I last tried to come up with a version of filter that works both the relative & absolute path it quickly became way to complicated and wasn't really intuitive either. I should probably revisit that topic at some point.

I hope that fixes your problem (if not, let me know), and thanks for using this, I'm glad it's useful for someone besides just me 😄.

**Comment by GavinRay97** [comment]
Ohh, understood, thank you!

> When I last tried to come up with a version of filter that works both the relative & absolute path it quickly became way to complicated and wasn't really intuitive either. I should probably revisit that topic at some point.

Maybe something like this?

```rs
use std::env; // for getting CWD

impl InliningFilter {
    pub fn should_inline(&mut self, path: &Path, is_system: bool) -> bool {
        let base_path = env::current_dir().expect("Failed to get current directory");
        let (set, infos) = if is_system {
            (&self.system_set, &self.system_infos)
        } else {
            (&self.quote_set, &self.quote_infos)
        };
        check_should_inline(path, set, infos, &mut self.indices, &base_path)
    }
}

fn check_should_inline(
    path: &Path,
    set: &GlobSet,
    infos: &[GlobInfo],
    indices: &mut Vec<usize>,
    base_path: &Path, // Add a parameter for the base path
) -> bool {
    let relative_path = if path.is_absolute() {
        path.to_path_buf()
    } else {
        base_path.join(path)
    };

    let candidate = Candidate::new(&relative_path);
    let log_name = debug_file_name(path);
    set.matches_candidate_into(&candidate, indices);
    if let Some(&idx) = indices.last() {
        let glob_str = &infos[idx].str;
        if infos[idx].inverted {
            debug!("Inlining {:?} (cause: '{}')", log_name, glob_str);
            true
        } else {
            debug!("Not inlining {:?} (cause: '{}')", log_name, glob_str);
            false
        }
    } else {
        debug!("Inlining {:?} by default", log_name);
        true
    }
}
```
